In [1]:
import numpy as np

### Materials referred:
Numpy Quickstart: https://numpy.org/doc/stable/user/quickstart.html

W3Schools: https://www.w3schools.com/python/numpy/numpy_creating_arrays.asp

### Array creation

In [2]:
# 1. python list to array
new_list = [0,1,2,4,6,9]

new_array = np.array(new_list)
array_direct = np.array([1,2,3,5,6,9])

print(new_array)
print(array_direct)

[0 1 2 4 6 9]
[1 2 3 5 6 9]


In [3]:
# list to 2-d array
new_list2 = [[1,2,6],[7,5,6]]
new_array2d = np.array(new_list2)

In [4]:
new_array2d

array([[1, 2, 6],
       [7, 5, 6]])

#### Basics 

In [5]:
# number of dimensions of an array
print(new_array.ndim)
print(new_array2d.ndim)
zero_d = np.array(1)
print(zero_d.ndim)

1
2
0


In [6]:
# shape of an array
print(new_array.shape)
print(new_array2d.shape)
print(zero_d.shape)

(6,)
(2, 3)
()


In [7]:
# data type of elements - could be Python's defaults or numpy's types
print(new_array.dtype)

int32


In [8]:
# number of elements
print(new_array.size)

6


In [9]:
list_com = [1, 'varchar']
com_array = np.array(list_com)

# numpy has priority in data types, unicode takes priority over int32
print(com_array.dtype)

<U11


^ for this, refer: https://stackoverflow.com/questions/49751000/how-does-numpy-determine-the-array-data-type-when-it-contains-multiple-dtypes

In [10]:
# bytes used by each element
print(new_array.itemsize)

4


### Back to array creation 

In [11]:
# np.array takes two arguments - list and dtype
complex_numbers = np.array([[1,2],[5,7]], dtype = complex)
complex_numbers

array([[1.+0.j, 2.+0.j],
       [5.+0.j, 7.+0.j]])

In [12]:
# array of zeros
zeroes = np.zeros((5,2))
zeroes

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
# array of ones
ones_array = np.ones((2,3), dtype=np.int16)
ones_array

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [14]:
# empty array, gets filled with values from memory, default type float64 but can be changed
nones = np.empty((2,4))
nones

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 6.79834329e-321, 1.57696599e-234,
        1.06099790e-311]])

In [15]:
# Arange
evens_10 = np.arange(0,10,2)
evens_10

array([0, 2, 4, 6, 8])

In [16]:
odds_10 = np.arange(1,10,2)
odds_10

array([1, 3, 5, 7, 9])

In [17]:
# Linspace - third argument takes the number of elements to be generate
linspace_array = np.linspace(0,100,7)
linspace_array

array([  0.        ,  16.66666667,  33.33333333,  50.        ,
        66.66666667,  83.33333333, 100.        ])

### Universal functions:

all, any, apply_along_axis, argmax, argmin, argsort, average, bincount, ceil, clip, conj, corrcoef, cov, cross, cumprod, cumsum, diff, dot, floor, inner, invert, lexsort, max, maximum, mean, median, min, minimum, nonzero, outer, prod, re, round, sort, std, sum, trace, transpose, var, vdot, vectorize, where

### Indexing and Slicing 

In [18]:
cubes = np.arange(10)**3
cubes

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [19]:
cubes[0]

0

In [20]:
cubes[:3]
# does not include the right limit, includes the left limit

array([0, 1, 8], dtype=int32)

In [21]:
cubes[1:10:3]

array([  1,  64, 343], dtype=int32)

In [22]:
cubes[-1]
# negative indexing works, just like lists

729

In [23]:
def integers(x,y):
    return(10*x+y)

In [24]:
ints = np.fromfunction(integers,(4,5),dtype=int)

In [25]:
ints
# values are calculated by using the indices as the inputs to the function

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [26]:
ints[:3,1]

array([ 1, 11, 21])

In [27]:
for row in ints[:3,]:
    print(row[1])

1
11
21


### Distributions 

In [ ]:
from nu